spring.application.name=tp5-client
server.port=8282

#configuration Spring gRPC official pour l'option A(Port Web 8181)
spring.grpc.client.channels.productClient.address=static://localhost:8181
spring.grpc.client.channels.productClient.securet=false